name: Branch Protection Rules

on:
  # This workflow can be triggered manually or as part of repository setup
  workflow_dispatch:

jobs:
  protect-main-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Branch Protection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Main branch protection configuration
            github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: {
                strict: true, // Require branches to be up to date before merging
                contexts: [
                  'ci/lint', // Example lint check
                  'ci/test', // Example test check
                  'ci/build' // Example build check
                ]
              },
              enforce_admins: true, // Enforce protection rules for admins too
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 2 // Require 2 approvals
              },
              restrictions: {
                // Optional: Limit who can push to the protected branch
                users: [], // Specific users
                teams: [], // Specific teams
                apps: []  // Specific GitHub Apps
              }
            });

  protect-develop-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Develop Branch Protection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Develop branch protection with slightly different rules
            github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'develop',
              required_status_checks: {
                strict: true,
                contexts: [
                  'ci/lint',
                  'ci/test'
                ]
              },
              enforce_admins: false, // More relaxed for develop branch
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                required_approving_review_count: 1 // Require 1 approval
              }
            });
